name: duello
version: 1.0
main: it.cerebotani.Main

commands:
  duello:
    description: "Comando per il duello"
    usage: "/duello <giocatore>"

  custommap:
    description: "Comando per la mappa verso la tazza dorata"
    usage: "/custommap"

  orbitalcannon:
    description: "Comando per annientare"
    usage: "/orbitalcannon"

listeners:
  - it.cerebotani.commands.Duello